# Generated by Django 3.2.5 on 2023-03-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_Management_App', '0003_project_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.BooleanField(choices=[(1, 'A'), (0, 'P')], default=False),
        ),
    ]
