# Generated by Django 3.2.5 on 2023-03-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_Management_App', '0004_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[(1, 'AVILABLE'), (2, 'REJECTED'), (0, 'PENDING')], default=0, max_length=20),
        ),
    ]
