# Generated by Django 3.2.5 on 2023-03-27 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_Management_App', '0005_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[(1, 'APPROVED'), (2, 'REJECTED'), (0, 'PENDING')], default=0, max_length=20),
        ),
        migrations.RemoveField(
            model_name='project',
            name='students',
        ),
        migrations.AddField(
            model_name='project',
            name='students',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_projects', to='Backend_Management_App.user'),
            preserve_default=False,
        ),
    ]
